### ISSUE TITLE
maybe should sort alphabetically?

### ISSUE THREAD

**Issue by johndpope** [zengyan-97/Sentiment-Lexicon#1]

**Comment by zengyan-97** [comment]
I will update it soon~

**Comment by johndpope** [comment]
you might be interested - I worked on a repo for mashing up vocab on a text.
https://github.com/johndpope/vocab-mashup

if you take a cartoon dialogue / say south park - and mash it together with a presidential speech it creates a hybrid. The maths / stats respects the distributions of text so the output sounds like south park even though it's a presidential speech eg.

![download](https://user-images.githubusercontent.com/289994/49688580-7a86af00-fae2-11e8-9907-317db467c000.jpeg)

https://gist.github.com/johndpope/f235f213ef5a0d47729cb8f57f966192
 
https://github.com/johndpope/vocab-mashup/issues/1

why does this matter - well - with these sentiments - you could easily take any text and color it in a negative or positive light. The vocab-mashup repo is using word2vec and POS identification. 

what also comes to mind is this library Bert-as-service which can break apart sentences....might be able to create a new mash up - to allow NLP researchers to color their pre-training texts in negative / positive lights.
https://github.com/hanxiao/bert-as-service/issues/95
